"""Power and energy calculations for solar production estimates."""

from __future__ import annotations

from collections.abc import Mapping
from datetime import datetime as dt

from pvlib import temperature

from .constants import ALPHA_TEMP, G_STC, TEMP_STC_CELL


def _quarter_hour_energy(
    average_power: Mapping[dt, int | float],
) -> dict[dt, float]:
    """Convert PT15M average power to energy for each exact interval."""
    return {timestamp: power * 0.25 for timestamp, power in average_power.items()}


def cell_temperature(gti: float, t_amb: float, wind: float) -> float:
    """Estimate the cell temperature from irradiance, ambient temp and wind.

    Uses pvlib's Faiman model (IEC 61853 standard), which accounts for
    convective cooling:
         Tc = Ta + G / (u0 + u1 * ws)

    References
    ----------
            - Faiman model: https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.temperature.faiman.html

    """
    return float(temperature.faiman(gti, t_amb, wind))


def gen_power(gti: float, t_amb: float, wind: float, eff: float, dc_wp: float) -> int:
    """Calculate the power generated by a solar panel.

    Formulas:
    ---------
        The cell temperature is estimated with the Faiman model; see
        cell_temperature().

    References
    ----------
            - Power output formula: P = Pmax * (G / Gstc) * (1 + α * (Tc - Tstc)) * ηDC (see p.509)
              Source: https://www.researchgate.net/publication/372240079_Solar_Prediction_Strategy_for_Managing_Virtual_Power_Stations

    """
    temp_cell = cell_temperature(gti, t_amb, wind)
    power = dc_wp
    power *= gti / G_STC
    power *= 1 + ALPHA_TEMP * (temp_cell - TEMP_STC_CELL)
    power *= eff
    return round(max(0, power))


def calculate_damping_coefficient(
    time: dt,
    sunrise: dt,
    sunset: dt,
    damping_morning: float,
    damping_evening: float,
) -> float:
    """Calculate the damping coefficient for the current time.

    Args:
    ----
        time: The current time.
        sunrise: The time of sunrise.
        sunset: The time of sunset.
        damping_morning: The damping factor for the morning.
        damping_evening: The damping factor for the evening.

    Returns:
    -------
        The damping coefficient for the current time.

    Notes:
    -----
        As the damping factor decreases, the power generated by the solar
        panels increases. For example, when the damping factor is 0, the
        power generated is at its maximum and no damping is applied. When
        the damping factor is 1, the power generated is at its minimum and
        the damping is fully applied.

        This means that if a damping factor of 1.0 is applied for the morning,
        at morning_start the power generated will be 0 as the coefficient would
        be 0.0. As the time approaches morning_end, the coefficient will increase
        linearly until it reaches 1.0 at morning_end. The same applies for the
        evening, but the coefficient will decrease linearly from 1.0 to 0.0.

    """
    morning_start = sunrise
    morning_end = sunrise + (sunset - sunrise) / 2
    evening_start = morning_end
    evening_end = sunset

    def linear_damping(start: dt, end: dt, damping: float) -> float:
        """Calculate the linear damping coefficient."""
        duration = end - start
        if not duration:
            return 1.0
        elapsed = time - start
        damping = 1.0 - damping
        return (elapsed / duration) * (1.0 - damping) + damping

    if morning_start <= time <= morning_end:
        return linear_damping(morning_start, morning_end, damping_morning)

    if evening_start <= time <= evening_end:
        return linear_damping(evening_end, evening_start, damping_evening)

    return 1


def diffuse_fraction(diffuse: float, direct: float) -> float:
    """Calculate the diffuse contribution to total irradiance."""
    if (diffuse + direct) > 0:
        return max(diffuse / (diffuse + direct), 0.0)
    return 1.0


def snowcover_factor(snow_depth_m: float, max_snowcover_depth_cm: float) -> float:
    """Calculate the irradiance reduction factor due to snow coverage."""
    return 1.0 - min((snow_depth_m * 100) / max_snowcover_depth_cm, 1.0)


def hourly_average_power(w_avg: Mapping[dt, int | float]) -> dict[dt, float]:
    """Calculate the average power generated per hour."""
    wh_period: dict[dt, float] = {}
    wh_period_count: dict[dt, int] = {}
    for time, power in w_avg.items():
        hour = time.replace(minute=0, second=0, microsecond=0)
        wh_period[hour] = wh_period.get(hour, 0) + power
        wh_period_count[hour] = wh_period_count.get(hour, 0) + 1
    for time in wh_period:
        wh_period[time] /= wh_period_count[time]
    return wh_period


def daily_energy(
    wh_period: Mapping[dt, int | float],
    wh_days: dict,
) -> dict:
    """Calculate the total energy produced per day."""
    for time, power in wh_period.items():
        day = time.date()
        wh_days[day] = wh_days.get(day, 0) + power
    return wh_days
