"""Power and energy calculations for solar production estimates."""

from __future__ import annotations

import logging
import warnings
from collections.abc import Mapping
from datetime import datetime as dt

import numpy
import pandas as pd
from pvlib import inverter, temperature

from .constants import (
    ALPHA_TEMP,
    DC_LOSS_FACTOR,
    ETA_INV_NOM,
    ETA_INV_REF,
    G_STC,
    TEMP_STC_CELL,
    WIND_SPEED_10M_TO_MODULE,
)

_LOGGER = logging.getLogger(__name__)

# Thermal-inertia smoothing needs a few consecutive samples to be meaningful.
_MIN_INERTIA_RUN = 4


def _quarter_hour_energy(
    average_power: Mapping[dt, int | float],
) -> dict[dt, float]:
    """Convert PT15M average power to energy for each exact interval."""
    return {timestamp: power * 0.25 for timestamp, power in average_power.items()}


def module_wind_speed(wind_10m: float) -> float:
    """Convert a 10 m wind speed to the module-height value Faiman expects.

    See ``WIND_SPEED_10M_TO_MODULE`` for why this is a fixed empirical ratio
    rather than a wind-profile power law.
    """
    return wind_10m * WIND_SPEED_10M_TO_MODULE


def cell_temperature(gti: float, t_amb: float, wind: float) -> float:
    """Estimate the cell temperature with the Faiman model (IEC 61853).

    ``wind`` is expected at module height; see :func:`module_wind_speed`.
    """
    return float(temperature.faiman(gti, t_amb, wind))


def _uniform_runs(
    index: pd.DatetimeIndex, min_length: int = _MIN_INERTIA_RUN
) -> list[tuple[int, int]]:
    """Split an index into ``[start, stop)`` runs of uniform spacing.

    Rows with incomplete weather data are dropped upstream, so the series can
    contain gaps. Several pvlib routines reject unequal intervals outright, so
    callers work run by run instead.
    """
    n = len(index)
    if n < min_length:
        return []

    deltas = index.to_series().diff().dt.total_seconds().to_numpy()
    runs: list[tuple[int, int]] = []
    start = 0
    for i in range(2, n):
        if deltas[i] != deltas[i - 1]:
            if i - start >= min_length:
                runs.append((start, i))
            # The next run needs its own leading interval, so it begins on
            # the previous sample.
            start = i - 1
    if n - start >= min_length:
        runs.append((start, n))
    return runs


def cell_temperature_series(
    times: pd.DatetimeIndex,
    gti: list[float],
    temp_air: list[float],
    wind_module: list[float],
    *,
    thermal_inertia: bool = False,
) -> numpy.ndarray:
    """Cell temperature for a whole series, optionally with thermal inertia.

    A module has real thermal mass, so its temperature lags the conditions
    driving it. The steady-state Faiman model ignores that, which matters when
    irradiance changes quickly: under broken cloud the two can differ by
    several degrees at an individual timestep.

    The effect on total energy is negligible (~0.05%) because the lag averages
    out, so this is applied only to the instantaneous power series, where it
    is physically meaningful.
    """
    poa = numpy.asarray(gti, dtype=float)
    air = numpy.asarray(temp_air, dtype=float)
    wind = numpy.asarray(wind_module, dtype=float)

    steady = numpy.asarray(temperature.faiman(poa, air, wind), dtype=float)
    if not thermal_inertia or len(times) < _MIN_INERTIA_RUN:
        return steady

    smoothed = steady.copy()
    for start, stop in _uniform_runs(times):
        span = times[start:stop]
        with warnings.catch_warnings():
            # pvlib declines to smooth intervals of 20 minutes or more and
            # says so; leaving those unchanged is the correct outcome.
            warnings.simplefilter("ignore")
            try:
                result = temperature.prilliman(
                    pd.Series(steady[start:stop], index=span),
                    pd.Series(wind[start:stop], index=span),
                )
            except (NotImplementedError, ValueError) as err:
                _LOGGER.debug("Skipping thermal inertia for one run: %s", err)
                continue
        smoothed[start:stop] = numpy.nan_to_num(
            result.to_numpy(), nan=steady[start:stop]
        )
    return smoothed


def gen_power_at_temp(
    gti: float, temp_cell: float, eff: float, dc_wp: float
) -> int:
    """DC power for an already-known cell temperature.

    Same model as :func:`gen_power`, but takes the cell temperature as an
    input so the whole series can be prepared in one vectorised pass.
    """
    power = dc_wp
    power *= gti / G_STC
    power *= 1 + ALPHA_TEMP * (temp_cell - TEMP_STC_CELL)
    power *= eff
    power *= DC_LOSS_FACTOR
    return round(max(0, power))


def gen_power(gti: float, t_amb: float, wind: float, eff: float, dc_wp: float) -> int:
    """Calculate the DC power generated by a solar panel.

    Includes the steady-state DC system losses (soiling, mismatch, wiring,
    connections, LID, nameplate tolerance) via ``DC_LOSS_FACTOR``. Without
    them the model describes a perfect array and over-predicts by ~9%.

    References
    ----------
            - Power output formula: P = Pmax * (G / Gstc) * (1 + α * (Tc - Tstc)) * ηDC (see p.509)
              Source: https://www.researchgate.net/publication/372240079_Solar_Prediction_Strategy_for_Managing_Virtual_Power_Stations

    """
    temp_cell = cell_temperature(gti, t_amb, wind)
    power = dc_wp
    power *= gti / G_STC
    power *= 1 + ALPHA_TEMP * (temp_cell - TEMP_STC_CELL)
    power *= eff
    power *= DC_LOSS_FACTOR
    return round(max(0, power))


def inverter_dc_input_limit(ac_wp: float, dc_wp: float) -> float:
    """Return the inverter's DC input limit (``pdc0``) in W.

    ``ac_wp`` is the inverter's AC nameplate. The PVWatts inverter model is
    parameterised by the DC input limit instead, and caps AC output at
    ``ETA_INV_NOM * pdc0``, so scaling up by the nominal efficiency makes the
    cap land exactly on the advertised AC rating.

    When no inverter capacity is configured we size the DC input limit to the
    array nameplate. That applies a realistic part-load efficiency curve
    without inventing a clipping threshold the user never asked for: an array
    only reaches nameplate DC at 1000 W/m² and 25°C cell temperature, which is
    rare in practice.
    """
    if ac_wp == float("inf"):
        return dc_wp
    return ac_wp / ETA_INV_NOM


def inverter_ac_power(pdc: float, pdc0: float) -> float:
    """Convert DC power to AC with the PVWatts inverter model.

    A hard ``min(P, capacity)`` clip treats the inverter as lossless below its
    rating, which over-predicts by ~4% at typical operating points and by far
    more at low load. The PVWatts curve uses NREL's statistical fit over
    inverters manufactured since 2010, so it needs no per-device calibration.
    """
    if pdc <= 0 or pdc0 <= 0:
        return 0.0

    # Clip the DC input to what the inverter can actually accept. Physically
    # the MPPT shifts off the maximum power point to limit input; numerically
    # this matters because the PVWatts efficiency polynomial is only valid up
    # to pdc/pdc0 ~ 1. Beyond roughly 60x its linear term drives the modelled
    # efficiency negative, and pvlib's floor at zero would then report an
    # over-panelled array as producing *nothing* instead of clipping.
    pdc = min(pdc, pdc0)

    return float(
        inverter.pvwatts(
            numpy.float64(pdc),
            numpy.float64(pdc0),
            eta_inv_nom=ETA_INV_NOM,
            eta_inv_ref=ETA_INV_REF,
        )
    )


def calculate_damping_coefficient(
    time: dt,
    sunrise: dt,
    sunset: dt,
    damping_morning: float,
    damping_evening: float,
) -> float:
    """Calculate the damping coefficient for the current time.

    Args:
    ----
        time: The current time.
        sunrise: The time of sunrise.
        sunset: The time of sunset.
        damping_morning: The damping factor for the morning.
        damping_evening: The damping factor for the evening.

    Returns:
    -------
        The damping coefficient for the current time.

    Notes:
    -----
        As the damping factor decreases, the power generated by the solar
        panels increases. For example, when the damping factor is 0, the
        power generated is at its maximum and no damping is applied. When
        the damping factor is 1, the power generated is at its minimum and
        the damping is fully applied.

        This means that if a damping factor of 1.0 is applied for the morning,
        at morning_start the power generated will be 0 as the coefficient would
        be 0.0. As the time approaches morning_end, the coefficient will increase
        linearly until it reaches 1.0 at morning_end. The same applies for the
        evening, but the coefficient will decrease linearly from 1.0 to 0.0.

    """
    morning_start = sunrise
    morning_end = sunrise + (sunset - sunrise) / 2
    evening_start = morning_end
    evening_end = sunset

    def linear_damping(start: dt, end: dt, damping: float) -> float:
        """Calculate the linear damping coefficient."""
        duration = end - start
        if not duration:
            return 1.0
        elapsed = time - start
        damping = 1.0 - damping
        return (elapsed / duration) * (1.0 - damping) + damping

    if morning_start <= time <= morning_end:
        return linear_damping(morning_start, morning_end, damping_morning)

    if evening_start <= time <= evening_end:
        return linear_damping(evening_end, evening_start, damping_evening)

    return 1


def diffuse_fraction(diffuse: float, direct: float) -> float:
    """Calculate the diffuse contribution to total irradiance."""
    if (diffuse + direct) > 0:
        return max(diffuse / (diffuse + direct), 0.0)
    return 1.0


def hourly_average_power(w_avg: Mapping[dt, int | float]) -> dict[dt, float]:
    """Calculate the average power generated per hour."""
    wh_period: dict[dt, float] = {}
    wh_period_count: dict[dt, int] = {}
    for time, power in w_avg.items():
        hour = time.replace(minute=0, second=0, microsecond=0)
        wh_period[hour] = wh_period.get(hour, 0) + power
        wh_period_count[hour] = wh_period_count.get(hour, 0) + 1
    for time in wh_period:
        wh_period[time] /= wh_period_count[time]
    return wh_period


def daily_energy(
    wh_period: Mapping[dt, int | float],
    wh_days: dict,
) -> dict:
    """Calculate the total energy produced per day."""
    for time, power in wh_period.items():
        day = time.date()
        wh_days[day] = wh_days.get(day, 0) + power
    return wh_days
